configuration:
  - Debug
  - Release

environment:
  apikey:
    secure: 4STrzCp6wDsDBj/wCtmImMVL7wUI8DCGjdMBXGqQf9JZJ8LjmW5YSY8wtcHAv0XW

branches:
  only:
    - master
    - develop

skip_tags: true

notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true

install:
  - tools\init.ps1 -v

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore

test:
  assemblies:
    - '**\bin\$(configuration)\*.test.dll'

artifacts:
  - path: src\VSSetup.PowerShell\bin\$(configuration)
    name: VSSetup
    type: zip

deploy:
  - provider: GitHub
    auth_token:
      secure: 5K94QY8dHKlbjvlBpQaXwAkmDf+LQE3g5WlU9snnNMjDjf0UT4xDoOBCLWcmwZOm
    artifact: VSSetup
    on:
      branch: master
      configuration: Release

after_deploy:
  - tools\publish.ps1 -configuration $(configuration) -apikey %apikey% -v

# vim: set ai et st=2 sts=2 sw=2:
